feat(request): move to using fetch
Power-My-Analytics/node-mailchimp pull request #1
Opened 2023-07-19 11:47 UTC by AmichayMiara

2023-07-20 06:28 UTC, talgryn requested changes

2023-07-20 06:28 UTC, talgryn commented on index.js
> +function request(options, callback) {
why did you had to import it inside the function?

2023-07-20 08:38 UTC, AmichayMiara commented on index.js
> +function request(options, callback) {
does not work other way

2023-07-23 07:44 UTC, talgryn approved these changes

2023-07-23 08:19 UTC, merged